### ISSUE TITLE
current soulseek clients are incompatible with museekd search responses

### ISSUE THREAD

**Issue by haggletonpie** [eLvErDe/museek-plus#5]
The old "original soulseek client"...

http://www.soulseekqt.net/news/node/683

...is compatible with museekd

The current client, SoulSeekQt, is not. (At least on Windows.)

I've confirmed that recent SoulSeekQt clients ignore the reply they get from museekd in response to a search request, rendering the entire museekd database invisible to anyone searching from the current Windows client. (Browse shares and transfers work though.)

I've only tested v. 2013-10-5 and v. 2014-8-31 and they both cannot search/find any museekd shares because they do not recognize the reply provided from museekd.

The old client can, though.

I'll update this issue as I test older versions of SoulSeekQt.  I don't have access to Linux or Mac desktop systems. (My museekd runs on a headless dedicated server.)

I sure hope this can be fixed. Museeq-plus is such a cool project.

Could this be a character set issue? I'm using the recommended defaults.

**Comment by foresto** [comment]
The current version of SoulseekQt also seems to ignore files larger than 2GiB in search responses. I wonder if this could be related.

**Comment by akhramov** [comment]
Hi! Any updates on this ticket? Can I help somehow? Any guidance will be appreciated.

**Comment by haggletonpie** [comment]
No updates, no further testing. Regarding the other thread, I agree that this is a crucial issue. museekd is a complete non-starter until this is addressed.

**Comment by haggletonpie** [comment]
@foresto @akhramov  

Any current interest in fixing this?

**Comment by akhramov** [comment]
@haggletonpie sorry for the very very late reply. I've tried to look into the error, but no luck...

**Comment by eLvErDe** [comment]
Hi,

Just merged lbponey pull request which is supposed to fix that.

**Comment by haggletonpie** [comment]
> pull request which is supposed to fix that

Whuh? The pull request notes say ...

> I initially hoped that I could fix museekd not sending search results to other clients. Unfortunately, it turns out this is probably blocked by the soulseek admins on the official server (the server doesn't send unofficial clients the information needed to connect to the search network). I've tried to make the code a little cleaner here anyway, we'll see if some day it is re-enabled.

https://github.com/eLvErDe/museek-plus/pull/35

Am I missing something?

**Comment by lbponey** [comment]
Thanks for merging!

@haggletonpie no you're not missing something, museekd can't send search results at the moment because the server doesn't send search requests.

When I hacked museekd to make the server believe it is the official client (which should *not* be done except for this kind of test), everything works fine (the client gets search requests and can send search results). That's why I think it's blocked at the server either:
- unintentionally
- because museekd was not enough respectful of the search network => I modified the code to make it more respectful

I guess someone could try to contact soulseek admin (nir?) and see if something can be done on their side

**Comment by haggletonpie** [comment]
> I guess someone could try to contact soulseek admin (nir?) and see if something can be done on their side

Posted to the soulseek google group...

https://groups.google.com/d/msg/soulseek-discussion/1IYboUSMZok/m6Bd1POkAAAJ

**Comment by AlxndrPsclt** [comment]
Hi! Just to let everyone know, I am currently working on a refactoring of the python bindings, to suit my specific automation needs. Will publish them when ready. I too hope this issue about sharing will be resolved at some point.   So I confirm there is renewed interest in museekd.

**Comment by anthonylauzon** [comment]
@lbponey how did you "hack" the museekd client to make the server think it was the official client?

**Comment by mathiascode** [comment]
I did some testing. If a Soulseek client identifies as version 179 or above (in the login message), the Soulseek server refuses to send a list of parents to connect to, which means we never receive global search requests. Museek+ currently identifies as version 183.

Directly searching a Museek+ user works, but there's a large issue which likely lead to Museek getting blacklisted, and also leads to SoulseekQt filtering our search results: all search results appear under the name of the recipient instead of our own username.

**Comment by mathiascode** [comment]
It seems like this issue went unnoticed for many years due to Soulseek NS automatically correcting the username.

**Comment by anthonylauzon** [comment]
Please see the changes in this file:

https://github.com/anthonylauzon/museek-plus/blob/e5102319c7373f9f430698dc7cd257d843fb95a6/museekd/servermessages.h

They should fix the issue.  I ran wireshark and inspected the connection diffs to yank the correct major and minor version numbers to send.

**Comment by GuillaumeLachaud** [comment]
@anthonylauzon Does this mean your fork is working correctly in regards to this issue ?

**Comment by mathiascode** [comment]
Using the official version number (@anthonylauzon's solution, also done in Nicotine+), or choosing a custom version number that still works (https://github.com/eLvErDe/museek-plus/pull/51) are both functional solutions, but doing so without addressing the the issue that likely led to the current version being blacklisted (fix at https://github.com/eLvErDe/museek-plus/pull/51/files#diff-19f6d7ce3ff27fb0c1c5c7123992e253165fffc2988ef4ed2968fc1b843af986R485) would be irresponsible.

**Comment by anthonylauzon** [comment]
> @anthonylauzon Does this mean your fork is working correctly in regards to this issue ?

yes the fork works.  i don't think any integer will work... it has to reflect the the correct major/minor numbers that the soulseekQT client uses.
